// Turns the SQL objects in sql/ into query text the app can run inline.
//
// The country workspaces read three objects that are defined in sql/ as a
// table function or a view. The service account the app runs with can read
// BigQuery but cannot create objects, so until each object is deployed the
// app runs the same body inline: the text between `AS (` and the closing `);`
// of the CREATE statement, with every `p_<name>` parameter rewritten to the
// query parameter `@<name>`. One source, two ways to run it. Run this after
// editing any of the files below; src/generated/sql.ts is committed so the
// build needs nothing.
//
// The product classification is one more object, sql/product_class.sql, a
// scalar function. The SQL files call it by name, which is what runs once
// they are deployed; here every call is expanded into the function's CASE,
// so the inline bodies need no routine. The same CASE is exported as
// PRODUCT_CLASS_BODY for the queries written in TypeScript
// (src/lib/product-class.ts), so the rule exists in one file only.
//
//   node scripts/build-sql.mjs          write src/generated/sql.ts
//   node scripts/build-sql.mjs --check  exit 1 if the generated file is stale
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/** file -> exported constant. The first CREATE in each file is the one taken. */
const SOURCES = [
  { file: "sql/capacity_week_v2.sql", name: "CAPACITY_WEEK_V2_BODY", kind: "function",
    types: { country: "STRING", month: "DATE", from: "DATE" } },
  { file: "sql/capacity_mason_week_v2.sql", name: "CAPACITY_MASON_WEEK_V2_BODY", kind: "function",
    types: { country: "STRING", level: "STRING", name: "STRING", start: "DATE", end: "DATE", weeks: "STRING" } },
  { file: "sql/cso_cash_daily_app_v1.sql", name: "CSO_CASH_DAILY_V1_BODY", kind: "view", types: {} },
];

const PRODUCT_CLASS_FILE = "sql/product_class.sql";
const PRODUCT_CLASS_CALL = "`earth-enable-main.raw_data_from_salesforce.product_class`(";
const PRODUCT_CLASS_PARAM = "product_interest";

/**
 * The app passes every query parameter as a string (src/lib/bigquery.ts sends
 * plain JS values, which BigQuery types as STRING), so a DATE parameter is
 * written as CAST(@name AS DATE) and a STRING one as @name.
 */
const paramExpr = (name, type) => (type === "STRING" ? `@${name}` : `CAST(@${name} AS ${type})`);

function body(sql, kind) {
  // The first CREATE statement, up to the line that is exactly ");" (function)
  // or the next CREATE / end of file (view).
  const start = sql.search(/^CREATE (OR REPLACE )?(TABLE FUNCTION|FUNCTION|VIEW)/m);
  if (start < 0) throw new Error("no CREATE statement");
  const rest = sql.slice(start);
  if (kind === "function") {
    const open = rest.indexOf("\nAS (");
    const close = rest.indexOf("\n);");
    if (open < 0 || close < 0) throw new Error("function body not found (expected 'AS (' and ');' on their own lines)");
    return rest.slice(open + "\nAS (".length, close);
  }
  const open = rest.search(/\nAS\s/);
  if (open < 0) throw new Error("view body not found");
  let text = rest.slice(open + 4);
  const next = text.search(/^CREATE /m);
  if (next >= 0) text = text.slice(0, next);
  return text.replace(/;\s*$/, "");
}

function params(text) {
  const names = new Set();
  for (const m of text.matchAll(/\bp_([a-z_]+)\b/g)) names.add(m[1]);
  return [...names].sort();
}

/** The classification CASE, with its parameter name left in place for the caller to substitute. */
const productClassBody = body(readFileSync(join(root, PRODUCT_CLASS_FILE), "utf8"), "function").trim();

/** Replace every `product_class`(<expr>) call with the CASE over <expr>, matching the call's own parentheses. */
function expandProductClass(text, file) {
  let out = "";
  let i = 0;
  for (;;) {
    const at = text.indexOf(PRODUCT_CLASS_CALL, i);
    if (at < 0) { out += text.slice(i); break; }
    out += text.slice(i, at);
    let depth = 1, j = at + PRODUCT_CLASS_CALL.length;
    for (; j < text.length && depth > 0; j++) {
      if (text[j] === "(") depth += 1;
      else if (text[j] === ")") depth -= 1;
    }
    if (depth !== 0) throw new Error(`${file}: unbalanced product_class( call`);
    const arg = text.slice(at + PRODUCT_CLASS_CALL.length, j - 1).trim();
    out += `(${productClassBody.replace(new RegExp(`\\b${PRODUCT_CLASS_PARAM}\\b`, "g"), `(${arg})`)})`;
    i = j;
  }
  return out;
}

const out = [
  "// GENERATED by scripts/build-sql.mjs from the files in sql/. Do not edit.",
  "// The body of each object, with `p_<name>` rewritten to `@<name>` and every",
  "// product_class(...) call expanded, so the app can run it inline until the",
  "// object is deployed to BigQuery.",
  "",
  `/** ${PRODUCT_CLASS_FILE} · the classification CASE; \`${PRODUCT_CLASS_PARAM}\` stands for the expression classified. */`,
  `export const PRODUCT_CLASS_BODY = ${JSON.stringify(productClassBody)};`,
  `export const PRODUCT_CLASS_PARAM = ${JSON.stringify(PRODUCT_CLASS_PARAM)};`,
  "",
];
for (const s of SOURCES) {
  const sql = readFileSync(join(root, s.file), "utf8");
  const text = expandProductClass(body(sql, s.kind).trim(), s.file);
  const ps = params(text);
  for (const p of ps) if (!s.types[p]) throw new Error(`${s.file}: no type declared for parameter p_${p}`);
  const inline = text.replace(/\bp_([a-z_]+)\b/g, (_, name) => paramExpr(name, s.types[name]));
  out.push(`/** ${s.file}${ps.length ? ` · parameters: ${ps.map((p) => `@${p} (${s.types[p]})`).join(", ")}` : ""} */`);
  out.push(`export const ${s.name} = ${JSON.stringify(inline)};`);
  out.push("");
}
const generated = out.join("\n");
const target = join(root, "src/generated/sql.ts");

if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(target, "utf8"); } catch { /* missing counts as stale */ }
  if (current !== generated) {
    console.error("src/generated/sql.ts is stale: run node scripts/build-sql.mjs");
    process.exit(1);
  }
  console.log("src/generated/sql.ts is up to date");
} else {
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, generated);
  console.log(`wrote ${target} (${generated.length} chars)`);
}
